version: "3"

services:
  agd:
    build: ./
    ports:
      - 5556:5556
    volumes:
      - ./:/agd
    networks:
      - web_humancam
    environment:
      - "params=${params}"
networks:
  web_humancam:
    external: true
